version: '3.8'

services:
  apache:
    build: ./apache
    container_name: ntlm-apache
    ports:
      - "8080:80"

  client:
    build: ./client
    container_name: ntlm-client
    depends_on:
      - apache
